apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "eth-gas-station.fullname" . }}-web
  labels:
    app: {{ template "eth-gas-station.name" . }}-web
    chart: {{ template "eth-gas-station.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "eth-gas-station.fullname" . }}-web
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  # - type: Pods
  #   pods:
  #     metricName: http_request_duration_milliseconds
  #     targetAverageValue: 300
