{{-  $secretConfig := include (print $.Template.BasePath "/config/_settings.docker.conf.yaml") . | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eth-gas-station.fullname" . }}
  labels:
    app: {{ template "eth-gas-station.name" . }}
    chart: {{ template "eth-gas-station.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  settings.conf: {{ $secretConfig.config | b64enc | quote }}
  sql_sa_credentials.json: {{ .Values.google.cloud_proxy.sql_sa_credentials_json | b64enc | quote }}
