apiVersion: v1
kind: Service
metadata:
  name: {{ template "eth-gas-station.fullname" . }}
  labels:
    app: {{ template "eth-gas-station.name" . }}
    chart: {{ template "eth-gas-station.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "eth-gas-station.name" . }}-web
    release: {{ .Release.Name }}
